#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_homepage:
    path: /
    controller: App\Controller\UserController::index

login:
    path:       /login
    controller: App\Controller\LoginController::login
    methods:    GET|POST

logout:
    path:       /logout
    controller: App\Controller\LoginController::logout
    methods:    GET|HEAD

registration:
    path:       /register
    controller: App\Controller\RegistrationController::register
    methods:    GET|POST

email_verification:
    path:       /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    methods:    GET|POST

user:
    path:       /user
    controller: App\Controller\UserController::index
    methods:    GET|HEAD

user_create:
    path:       /user_create
    controller: App\Controller\UserController::createUser
    methods:    PUT

user_show:
    path:       /user_show/{id}
    controller: App\Controller\UserController::showUser
    methods:    GET
