#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login:
    path:       /login
    controller: App\Controller\LoginController::index
    methods:    GET|HEAD

registration:
    path:       /register
    controller: App\Controller\RegisterController::index
    methods:    GET|POST

user:
    path:       /user
    controller: App\Controller\UserController::index
    methods:    GET|HEAD

user_create:
    path:       /user_create
    controller: App\Controller\UserController::createUser
    methods:    PUT

user_show:
    path:       /user_show/{id}
    controller: App\Controller\UserController::showUser
    methods:    GET
