#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_homepage:
    path: /
    controller: App\Controller\UserController::index

login:
    path:       /login
    controller: App\Controller\LoginController::login
    methods:    GET|POST

logout:
    path:       /logout
    controller: App\Controller\LoginController::logout
    methods:    GET|HEAD

registration:
    path:       /register
    controller: App\Controller\RegistrationController::register
    methods:    GET|POST

email_verification:
    path:       /verify/email
    controller: App\Controller\RegistrationController::verifyUserEmail
    methods:    GET|POST

# User routes:
user_index:
    path:       /user
    controller: App\Controller\UserController::index
    methods:    GET|HEAD
user_new:
    path:       /user/new
    controller: App\Controller\UserController::new
    methods:    GET|POST
user_show:
    path:       /user/{user}
    controller: App\Controller\UserController::show
    methods:    GET
user_edit:
    path:       /user/{user}/edit
    controller: App\Controller\UserController::edit
    methods:    GET|POST
user_delete:
    path:       /user/{user}
    controller: App\Controller\UserController::delete
    methods:    POST

# Vendor routes:
vendor_index:
    path:       /vendor
    controller: App\Controller\VendorController::index
    methods:    GET
vendor_new:
    path:       /vendor/new
    controller: App\Controller\VendorController::new
    methods:    GET|POST
vendor_show:
    path:       /vendor/{vendor}
    controller: App\Controller\VendorController::show
    methods:    GET
vendor_edit:
    path:       /vendor/{vendor}/edit
    controller: App\Controller\VendorController::edit
    methods:    GET|POST
vendor_delete:
    path:       /vendor/{vendor}
    controller: App\Controller\VendorController::delete
    methods:    POST
